name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Linting
        run: cargo clippy -- -D warnings
      - name: Tests
        run: cargo test

  features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --all-features
      - name: Tests
        run: cargo test --all-features
