name: Continuous Integration

# Runs for each commit/PR, but not tag push
on:
  push:
    branches:
      - "**"
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: Check (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      - name: Run Check
        run: cargo check

  test-suite:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.39.0
          - 1.88.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
        with:
          toolchain: ${{ matrix.rust }}
      - name: Run Tests with All Features
        run: cargo test --all-features
      - name: Run Tests with No Default Features
        run: cargo test --no-default-features

  test-suite-os:
    name: Test Suite (stable)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      - name: Run Test
        run: cargo test

  fmt:
    name: Rustfmt (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      - run: rustup component add rustfmt
      - name: Run Rustfmt
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      - name: Run Clippy
        run: cargo clippy -- -D warnings
