language: rust
rust:
  - stable
  - nightly
script:
  - |
    if [[ $TRAVIS_RUST_VERSION == *stable* ]]
    then
      rustup component add rustfmt
      cargo fmt --version
      cargo fmt -- --check || (echo "Please reformat your code with 'cargo fmt' (version $(cargo fmt --version))"; false)
    fi
  - cargo test
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] ||
    cargo test --all-features
